App.Views.HomePageView = Backbone.View.extend({
  el: 'body',
  className: 'sans full-size',
  initialize: function() {
    // Prevent this view from rendering if manually navigating
    // to urls after a previous visit to the home page.
    if(App.homePageRendered) return this.remove();

    App.menuClickable = true;
    this.html = App.templates.HomePageView();
    this.render();
  },
  render: function() {
    console.log('HomePageView.js');
    // something
    this.$el.html(this.html);
  },
  events: {
    'click #menu-json a': 'menuClicked'
  },
  menuClicked: function(e) {
    e.preventDefault();

    // Menu is clickable only after the cursor drops.
    if(!App.menuClickable) return;

    // Prevent multiple views being generated by
    // clicking a menu item more than once.
    App.menuClickable = false;
    var view = $(e.target).data('view');

    // Allow regular links to work, then quickly exit.
    if(!view) return;

    App.currentView = new App.Views[view]();
  }
});